<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>WinExe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>CA1416</NoWarn>
    <ApplicationIcon>..\..\installer\printer.ico</ApplicationIcon>
    <AssemblyTitle>Local Print Service</AssemblyTitle>
    <Product>Local Print Service</Product>
    <Description>Universal Print Service for Windows - Local Print Server</Description>
    <Version>1.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.29" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="8.0.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LocalPrintService.Domain\LocalPrintService.Domain.csproj" />
    <ProjectReference Include="..\LocalPrintService.Application\LocalPrintService.Application.csproj" />
    <ProjectReference Include="..\LocalPrintService.Infrastructure\LocalPrintService.Infrastructure.csproj" />
    <ProjectReference Include="..\LocalPrintService.Shared\LocalPrintService.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="certs\**" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
